# GET http://localhost:3001/api/persons
# DELETE http://localhost:3001/api/persons/2

POST https://protected-tor-18583.herokuapp.com/api/persons
Content-Type: application/json

{
    "name":"Jari", 
    "number":"0435355343"
}